# Generated by Django 4.1.7 on 2023-02-28 18:54
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcard',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
