# Generated by Django 4.1.7 on 2023-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_visitcard_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='director',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='visitcard',
            name='is_org',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitcard',
            name='type_activ',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
