# Generated by Django 4.1.7 on 2023-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_visitcard_address_visitcard_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcard',
            name='site_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
